use std::fmt;

use super::{ShaderMetadata, ShaderName, ShaderReflection, ShaderStageKind};
use crate::ShaderDiagnostic;

/// Compiled shader program output.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CompiledShaderProgram {
    /// Program name associated with this compiled output.
    shader_name: ShaderName,
    /// Stable cache key for this compiled output.
    cache_key: ShaderCacheKey,
    /// Compiled stage outputs.
    stages: Box<[CompiledShaderStage]>,
    /// Merged program metadata.
    metadata: ShaderMetadata,
    /// Merged program reflection.
    reflection: ShaderReflection,
    /// Program-level diagnostics emitted during compilation.
    diagnostics: Box<[ShaderDiagnostic]>,
}

impl CompiledShaderProgram {
    /// Creates compiled shader program output.
    #[must_use]
    pub fn new(
        shader_name: ShaderName,
        stages: Box<[CompiledShaderStage]>,
        diagnostics: Box<[ShaderDiagnostic]>,
    ) -> Self {
        Self {
            shader_name,
            cache_key: ShaderCacheKey::new("uncached"),
            stages,
            metadata: ShaderMetadata::default(),
            reflection: ShaderReflection::default(),
            diagnostics,
        }
    }

    /// Creates compiled shader program output with pipeline metadata.
    #[must_use]
    pub fn with_pipeline_outputs(
        shader_name: ShaderName,
        cache_key: ShaderCacheKey,
        stages: Box<[CompiledShaderStage]>,
        metadata: ShaderMetadata,
        reflection: ShaderReflection,
        diagnostics: Box<[ShaderDiagnostic]>,
    ) -> Self {
        Self {
            shader_name,
            cache_key,
            stages,
            metadata,
            reflection,
            diagnostics,
        }
    }

    /// Returns the shader name.
    #[must_use]
    pub const fn shader_name(&self) -> &ShaderName {
        &self.shader_name
    }

    /// Returns the stable cache key for this compiled output.
    #[must_use]
    pub const fn cache_key(&self) -> &ShaderCacheKey {
        &self.cache_key
    }

    /// Returns compiled stages.
    #[must_use]
    pub fn stages(&self) -> &[CompiledShaderStage] {
        &self.stages
    }

    /// Returns merged program metadata.
    #[must_use]
    pub const fn metadata(&self) -> &ShaderMetadata {
        &self.metadata
    }

    /// Returns merged program reflection.
    #[must_use]
    pub const fn reflection(&self) -> &ShaderReflection {
        &self.reflection
    }

    /// Returns program diagnostics.
    #[must_use]
    pub fn diagnostics(&self) -> &[ShaderDiagnostic] {
        &self.diagnostics
    }
}

/// Stable shader program cache key.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(transparent)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct ShaderCacheKey(String);

impl ShaderCacheKey {
    /// Creates an opaque shader cache key from a stable encoded value.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Returns the encoded cache key.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ShaderCacheKey {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for ShaderCacheKey {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Ok(Self(String::deserialize(deserializer)?))
    }
}

/// Compiled shader stage output.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CompiledShaderStage {
    /// Stage this output was compiled for.
    kind: ShaderStageKind,
    /// SPIR-V words generated by the compiler backend.
    spirv: Box<[u32]>,
    /// Optional source emitted by the legalization pass.
    legalized_source: Option<String>,
    /// Stage-level diagnostics emitted during compilation.
    diagnostics: Box<[ShaderDiagnostic]>,
}

impl CompiledShaderStage {
    /// Creates compiled shader stage output.
    #[must_use]
    pub fn new(
        kind: ShaderStageKind,
        spirv: Box<[u32]>,
        legalized_source: Option<String>,
        diagnostics: Box<[ShaderDiagnostic]>,
    ) -> Self {
        Self {
            kind,
            spirv,
            legalized_source,
            diagnostics,
        }
    }

    /// Returns the stage kind.
    #[must_use]
    pub const fn kind(&self) -> ShaderStageKind {
        self.kind
    }

    /// Returns the SPIR-V words.
    #[must_use]
    pub fn spirv(&self) -> &[u32] {
        &self.spirv
    }

    /// Returns the optional legalized source.
    #[must_use]
    pub fn legalized_source(&self) -> Option<&str> {
        self.legalized_source.as_deref()
    }

    /// Returns stage diagnostics.
    #[must_use]
    pub fn diagnostics(&self) -> &[ShaderDiagnostic] {
        &self.diagnostics
    }
}

/// Backend compiler artifact with public stage output and backend module.
#[derive(Clone, Debug, PartialEq)]
pub struct CompiledStageArtifact<M> {
    /// Public compiled stage payload.
    stage: CompiledShaderStage,
    /// Backend-specific module retained for reflection.
    module: M,
    /// Backend diagnostics associated with the artifact.
    diagnostics: Box<[ShaderDiagnostic]>,
}

impl<M> CompiledStageArtifact<M> {
    /// Creates a compiled stage artifact.
    #[must_use]
    pub const fn new(
        stage: CompiledShaderStage,
        module: M,
        diagnostics: Box<[ShaderDiagnostic]>,
    ) -> Self {
        Self {
            stage,
            module,
            diagnostics,
        }
    }

    /// Returns the stage kind.
    #[must_use]
    pub const fn kind(&self) -> ShaderStageKind {
        self.stage.kind()
    }

    /// Returns the public compiled stage payload.
    #[must_use]
    pub const fn stage(&self) -> &CompiledShaderStage {
        &self.stage
    }

    /// Returns the backend module.
    #[must_use]
    pub const fn module(&self) -> &M {
        &self.module
    }

    /// Consumes the artifact and returns the backend module.
    #[must_use]
    pub fn into_module(self) -> M {
        self.module
    }

    /// Returns artifact diagnostics.
    #[must_use]
    pub fn diagnostics(&self) -> &[ShaderDiagnostic] {
        &self.diagnostics
    }
}
