use std::{
    borrow::Cow,
    collections::{BTreeMap, BTreeSet},
};

use crate::{
    ShaderError, ShaderResult, ShaderStageKind,
    legalize::{SamplerType, StageResourceLayout, TokenSearch, UniformMember},
    lexer::{Token, TokenKind},
    pipeline::inputs::ProgramStageInputs,
    preprocess::PreprocessedStage,
    syntax::{ShaderModule, SyntaxItem, TopLevelQualifier},
};

/// Program-level descriptor layout for resources generated by legalization.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProgramResourceLayout<'src> {
    /// Shared binding for generated `GlobalUniforms`, when any stage needs it.
    uniform_block_binding: Option<u32>,
    /// Program-wide set zero descriptor bindings reserved by kept source
    /// resources.
    reserved_bindings: BTreeSet<u32>,
    /// Program-wide descriptor bindings assigned to generated split textures.
    texture_bindings: ProgramTextureResourceBindings<'src>,
    /// Program-wide members for generated `GlobalUniforms`.
    uniform_members: Vec<UniformMember<'src>>,
}

impl<'src> ProgramResourceLayout<'src> {
    /// Builds program-wide resource bindings from all parsed stage
    /// declarations.
    pub(super) fn from_inputs(stage_inputs: &ProgramStageInputs<'src>) -> ShaderResult<Self> {
        let stages = stage_inputs.stages();
        let mut reservations = ProgramBindingReservations::default();
        let mut explicit_uniform_binding = None;
        let mut uniform_members = Vec::new();
        let mut uniform_member_names = BTreeMap::new();
        let mut textures = Vec::new();

        for kind in [ShaderStageKind::Vertex, ShaderStageKind::Fragment] {
            for stage in stages.iter().filter(|stage| stage.stage.kind() == kind) {
                for item in stage.module.items() {
                    let SyntaxItem::Declaration(declaration) = item else {
                        continue;
                    };
                    match (ProgramResourceDeclaration {
                        module: &stage.module,
                        declaration,
                    })
                    .kind()
                    {
                        ProgramResourceDeclarationKind::Texture(texture) => {
                            if let Some(binding) = texture.encoded_binding() {
                                binding.reserve_for(texture, &mut reservations)?;
                            }
                            textures.push(ProgramTextureResource {
                                stage: kind,
                                declaration: texture,
                            });
                        }
                        ProgramResourceDeclarationKind::UniformMember(uniform) => {
                            let member = uniform.into_supported_member()?;
                            if let Some(previous) = uniform_member_names.get(member.name).copied() {
                                if !member.has_same_layout(&uniform_members[previous]) {
                                    return Err(ShaderError::invalid_request(
                                        "conflicting GlobalUniforms member declarations",
                                    ));
                                }
                            } else {
                                let _old =
                                    uniform_member_names.insert(member.name, uniform_members.len());
                                uniform_members.push(member.into_uniform_member());
                            }
                            if let Some(binding) = uniform.explicit_binding() {
                                if let Some(previous) = explicit_uniform_binding
                                    && previous != binding
                                {
                                    return Err(ShaderError::invalid_request(
                                        "conflicting explicit GlobalUniforms descriptor bindings",
                                    ));
                                }
                                explicit_uniform_binding = Some(binding);
                            }
                        }
                        ProgramResourceDeclarationKind::KeptResource(resource) => {
                            if let Some(binding) = resource.layout_binding {
                                binding.reserve_for(resource, &mut reservations)?;
                            }
                        }
                        ProgramResourceDeclarationKind::Other => {}
                    }
                }
            }
        }

        let reserved_bindings = reservations.set_zero_binding_indices().collect();
        let uniform_block_binding = if uniform_members.is_empty() {
            None
        } else {
            let binding = explicit_uniform_binding.unwrap_or_else(|| {
                let mut binding = 0u32;
                while reservations.contains_binding(binding) {
                    binding += 1;
                }
                binding
            });
            reservations.reserve(
                binding,
                ProgramBindingReservation {
                    name: "GlobalUniforms",
                    kind: ProgramBindingReservationKind::GeneratedUniformBlock,
                },
            )?;
            Some(binding)
        };

        let mut allocator = ProgramResourceAllocator { reservations };
        let texture_bindings = ProgramTextureResourceBindings {
            assignments: allocator.assign_textures(textures)?,
        };

        Ok(Self {
            uniform_block_binding,
            reserved_bindings,
            texture_bindings,
            uniform_members,
        })
    }
}

impl Default for ProgramResourceLayout<'_> {
    fn default() -> Self {
        static EMPTY_STAGES: [PreprocessedStage; 0] = [];

        let inputs = ProgramStageInputs::try_from(EMPTY_STAGES.as_slice())
            .expect("empty stage inputs parse");
        Self::from_inputs(&inputs).expect("empty resource layout builds")
    }
}

impl<'src> ProgramResourceLayout<'src> {
    /// Builds the legalizer-facing resource layout for one stage.
    pub(super) fn stage_layout(&self) -> StageResourceLayout<'src> {
        let mut layout = StageResourceLayout::default();
        layout.uniform_block_binding = self.uniform_block_binding;
        layout.reserved_bindings.clone_from(&self.reserved_bindings);
        layout.uniform_members.clone_from(&self.uniform_members);
        for assignment in self.texture_bindings.assignments.iter().copied() {
            layout.push_texture_binding(
                assignment.stage,
                assignment.name,
                assignment.texture_binding,
                assignment.sampler_binding,
            );
        }
        layout
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resource_layout_constructor_accepts_empty_stage_inputs() {
        let stages = Vec::<PreprocessedStage>::new();
        let inputs = ProgramStageInputs::try_from(stages.as_slice()).expect("empty inputs parse");
        let layout = ProgramResourceLayout::from_inputs(&inputs).expect("empty layout builds");

        assert_eq!(layout, ProgramResourceLayout::default());
    }
}

/// Program-wide split texture descriptor assignments.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramTextureResourceBindings<'src> {
    /// Assignments in deterministic stage/source order.
    assignments: Vec<ProgramTextureResourceBinding<'src>>,
}

/// Program-level split texture resource tagged with its owning stage.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramTextureResource<'src> {
    /// Stage containing the source texture declaration.
    stage: ShaderStageKind,
    /// Source texture declaration.
    declaration: TextureResourceDeclaration<'src>,
}

/// Program-level descriptor binding assignment for one split texture.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramTextureResourceBinding<'src> {
    /// Stage containing the source declaration.
    stage: ShaderStageKind,
    /// Source texture variable name.
    name: &'src str,
    /// Descriptor binding assigned to the generated texture handle.
    texture_binding: u32,
    /// Descriptor binding assigned to the generated sampler.
    sampler_binding: u32,
}

/// Program-wide descriptor binding allocator for generated resources.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramResourceAllocator<'src> {
    /// Descriptor bindings already occupied in the program.
    reservations: ProgramBindingReservations<'src>,
}

impl<'src> ProgramResourceAllocator<'src> {
    /// Assigns texture and generated sampler descriptor bindings for all
    /// split texture declarations, reusing one logical resource assignment
    /// when the same source texture appears in multiple stages.
    fn assign_textures(
        &mut self,
        textures: Vec<ProgramTextureResource<'src>>,
    ) -> ShaderResult<Vec<ProgramTextureResourceBinding<'src>>> {
        let mut by_name: BTreeMap<&'src str, ProgramTextureResourceBinding<'src>> = BTreeMap::new();
        let mut assignments = Vec::with_capacity(textures.len());
        for texture in textures {
            if let Some(previous) = by_name.get(texture.declaration.name).copied() {
                assignments.push(ProgramTextureResourceBinding {
                    stage: texture.stage,
                    name: texture.declaration.name,
                    texture_binding: previous.texture_binding,
                    sampler_binding: previous.sampler_binding,
                });
                continue;
            }

            let assignment = self.assign_texture(texture)?;
            let _old = by_name.insert(texture.declaration.name, assignment);
            assignments.push(assignment);
        }
        Ok(assignments)
    }

    /// Assigns texture and generated sampler descriptor bindings for one
    /// split texture declaration.
    fn assign_texture(
        &mut self,
        texture: ProgramTextureResource<'src>,
    ) -> ShaderResult<ProgramTextureResourceBinding<'src>> {
        let texture_binding = if let Some(binding) = texture.declaration.encoded_binding() {
            binding.reserve_for(texture.declaration, &mut self.reservations)?;
            binding.descriptor.binding
        } else {
            self.allocate(ProgramBindingReservation {
                name: texture.declaration.name,
                kind: ProgramBindingReservationKind::GeneratedTexture,
            })
        };
        let sampler_binding = self.allocate(ProgramBindingReservation {
            name: texture.declaration.name,
            kind: ProgramBindingReservationKind::GeneratedSampler,
        });

        Ok(ProgramTextureResourceBinding {
            stage: texture.stage,
            name: texture.declaration.name,
            texture_binding,
            sampler_binding,
        })
    }

    /// Allocates the lowest unoccupied binding.
    fn allocate(&mut self, reservation: ProgramBindingReservation<'src>) -> u32 {
        let mut binding = 0u32;
        while self.reservations.contains_binding(binding) {
            binding += 1;
        }
        self.reservations
            .reserve(binding, reservation)
            .expect("fresh descriptor binding should be reservable");
        binding
    }
}

/// Program-wide descriptor binding reservations keyed by set and binding
/// number.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
struct ProgramBindingReservations<'src> {
    /// Reservation identity for each occupied binding.
    bindings: BTreeMap<ProgramDescriptorBinding, ProgramBindingReservation<'src>>,
}

impl<'src> ProgramBindingReservations<'src> {
    /// Reserves one descriptor binding for a typed logical resource.
    fn reserve(
        &mut self,
        binding: u32,
        reservation: ProgramBindingReservation<'src>,
    ) -> ShaderResult<()> {
        self.reserve_descriptor(ProgramDescriptorBinding::set_zero(binding), reservation)
    }

    /// Reserves one descriptor set/binding pair for a typed logical resource.
    fn reserve_descriptor(
        &mut self,
        descriptor: ProgramDescriptorBinding,
        reservation: ProgramBindingReservation<'src>,
    ) -> ShaderResult<()> {
        if let Some(previous) = self.bindings.get(&descriptor) {
            if *previous == reservation {
                return Ok(());
            }
            return Err(ShaderError::invalid_request(
                "descriptor binding is already reserved by an incompatible resource",
            ));
        }
        let _previous = self.bindings.insert(descriptor, reservation);
        Ok(())
    }

    /// Returns whether any resource already occupies `binding`.
    fn contains_binding(&self, binding: u32) -> bool {
        self.bindings
            .contains_key(&ProgramDescriptorBinding::set_zero(binding))
    }

    /// Iterates occupied set zero binding numbers.
    fn set_zero_binding_indices(&self) -> impl Iterator<Item = u32> + '_ {
        self.bindings
            .keys()
            .filter(|descriptor| descriptor.set == 0)
            .map(|descriptor| descriptor.binding)
    }
}

/// Descriptor set/binding pair used by program-wide reservations.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct ProgramDescriptorBinding {
    /// Descriptor set index.
    set: u32,
    /// Descriptor binding index within the set.
    binding: u32,
}

impl ProgramDescriptorBinding {
    /// Creates a set zero descriptor binding.
    const fn set_zero(binding: u32) -> Self {
        Self { set: 0, binding }
    }
}

/// Typed logical identity for a program descriptor binding reservation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramBindingReservation<'src> {
    /// Source or generated resource name.
    name: &'src str,
    /// Descriptor/resource kind occupying the binding.
    kind: ProgramBindingReservationKind<'src>,
}

/// Descriptor/resource kind included in binding reservation identity.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ProgramBindingReservationKind<'src> {
    /// Texture descriptor generated from a source `sampler2D`.
    SplitTexture {
        /// Generated backend texture type.
        ty: &'static str,
    },
    /// Kept source descriptor resource.
    KeptResource {
        /// Source resource type.
        ty: &'src str,
    },
    /// Generated `GlobalUniforms` descriptor.
    GeneratedUniformBlock,
    /// Generated texture descriptor without an encoded binding.
    GeneratedTexture,
    /// Generated sampler paired with a split texture.
    GeneratedSampler,
}

/// Parsed program-level resource declaration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramResourceDeclaration<'module, 'src> {
    /// Parsed module containing the declaration.
    module: &'module ShaderModule<'src>,
    /// Source declaration.
    declaration: &'module crate::syntax::ShaderDeclaration<'src>,
}

impl<'src> ProgramResourceDeclaration<'_, 'src> {
    /// Classifies the declaration as a resource kind used by program layout.
    fn kind(self) -> ProgramResourceDeclarationKind<'src> {
        if self.declaration.qualifier() != Some(TopLevelQualifier::Uniform) {
            return ProgramResourceDeclarationKind::Other;
        }
        match (self.declaration.type_name(), self.declaration.name()) {
            (Some(ty), Some(name)) => {
                if let Some(sampler) = SamplerType::new(ty) {
                    if sampler.supports_texture_split() {
                        ProgramResourceDeclarationKind::Texture(TextureResourceDeclaration {
                            name,
                            binding: TextureBindingName { name }.fact(),
                        })
                    } else {
                        ProgramResourceDeclarationKind::KeptResource(KeptResourceDeclaration {
                            ty,
                            name,
                            layout_binding: LayoutBindingFact::from_declaration(
                                self.module,
                                self.declaration,
                            ),
                        })
                    }
                } else {
                    ProgramResourceDeclarationKind::UniformMember(UniformResourceDeclaration {
                        stage: self.module.stage(),
                        module_source: self.module.source().as_str(),
                        ty,
                        name,
                        array_suffix: self.declaration.array_suffix().map(|suffix| {
                            ProgramArraySuffixFact {
                                source: suffix.as_str(),
                            }
                        }),
                        explicit_binding: LayoutBindingFact::from_declaration(
                            self.module,
                            self.declaration,
                        )
                        .map(|fact| fact.binding),
                    })
                }
            }
            _ => ProgramResourceDeclarationKind::Other,
        }
    }
}

/// Supported program-wide uniform block member declaration.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ProgramUniformMember<'src> {
    /// Source type name.
    ty: &'src str,
    /// Source variable name.
    name: &'src str,
    /// Optional array suffix following the declaration name.
    array_suffix: Option<Cow<'src, str>>,
    /// Explicit layout binding parsed from source, when present.
    explicit_binding: Option<u32>,
}

impl<'src> ProgramUniformMember<'src> {
    /// Returns whether another declaration would occupy the same block layout.
    fn has_same_layout(&self, other: &UniformMember<'_>) -> bool {
        ProgramUniformType::new(other.ty).is_ok_and(|other_ty| self.ty == other_ty.source)
            && self.name == other.name
            && self.array_suffix.as_deref() == other.array_suffix.as_deref()
    }

    /// Converts this supported declaration into the legalizer resource model.
    fn into_uniform_member(self) -> UniformMember<'src> {
        UniformMember {
            ty: self.ty,
            name: self.name,
            array_suffix: self.array_suffix,
            explicit_binding: self.explicit_binding,
            binding: None,
        }
    }
}

/// Supported uniform type names for generated std140 program uniforms.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramUniformType<'src> {
    /// Source type spelling.
    source: &'src str,
}

impl<'src> ProgramUniformType<'src> {
    /// Returns a supported type or rejects user-defined/opaque types before
    /// they can be emitted into a stage that cannot see their declarations.
    fn new(source: &'src str) -> ShaderResult<Self> {
        if matches!(
            source.as_bytes(),
            b"float"
                | b"float1"
                | b"float2"
                | b"float3"
                | b"float4"
                | b"vec2"
                | b"vec3"
                | b"vec4"
                | b"mat2"
                | b"mat3"
                | b"mat4"
                | b"mat2x2"
                | b"mat2x3"
                | b"mat2x4"
                | b"mat3x2"
                | b"mat3x3"
                | b"mat3x4"
                | b"mat4x2"
                | b"mat4x3"
                | b"mat4x4"
                | b"int"
                | b"ivec2"
                | b"ivec3"
                | b"ivec4"
                | b"uint"
                | b"uvec2"
                | b"uvec3"
                | b"uvec4"
                | b"bool"
                | b"bvec2"
                | b"bvec3"
                | b"bvec4"
        ) {
            Ok(Self { source })
        } else {
            Err(ShaderError::invalid_request(format!(
                "unsupported GlobalUniforms member type `{source}`"
            )))
        }
    }
}

/// Program-level resource declaration kind.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ProgramResourceDeclarationKind<'src> {
    /// Texture resource with an optional encoded binding.
    Texture(TextureResourceDeclaration<'src>),
    /// Scalar/vector uniform that contributes to `GlobalUniforms`.
    UniformMember(UniformResourceDeclaration<'src>),
    /// Kept descriptor resource with an optional explicit binding.
    KeptResource(KeptResourceDeclaration<'src>),
    /// Any declaration that does not participate in descriptor layout.
    Other,
}

/// Program-level texture declaration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TextureResourceDeclaration<'src> {
    /// Source texture name.
    name: &'src str,
    /// Binding fact encoded in the source name.
    binding: Option<TextureBindingFact<'src>>,
}

impl<'src> TextureResourceDeclaration<'src> {
    /// Returns this texture's typed binding reservation identity.
    const fn reservation(self) -> ProgramBindingReservation<'src> {
        ProgramBindingReservation {
            name: self.name,
            kind: ProgramBindingReservationKind::SplitTexture { ty: "texture2D" },
        }
    }

    /// Returns the encoded descriptor binding fact.
    const fn encoded_binding(self) -> Option<TextureBindingFact<'src>> {
        self.binding
    }
}

/// Program-level resource declaration kept in source.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct KeptResourceDeclaration<'src> {
    /// Source resource type.
    ty: &'src str,
    /// Source resource name.
    name: &'src str,
    /// Explicit descriptor binding parsed from the syntax layout fact.
    layout_binding: Option<LayoutBindingFact>,
}

impl<'src> KeptResourceDeclaration<'src> {
    /// Returns this resource's typed binding reservation identity.
    const fn reservation(self) -> ProgramBindingReservation<'src> {
        ProgramBindingReservation {
            name: self.name,
            kind: ProgramBindingReservationKind::KeptResource { ty: self.ty },
        }
    }
}

/// Texture name that may encode a fixed descriptor binding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TextureBindingName<'src> {
    /// Source texture name.
    name: &'src str,
}

impl<'src> TextureBindingName<'src> {
    /// Parses `g_TextureN` names into typed fixed binding facts.
    fn fact(self) -> Option<TextureBindingFact<'src>> {
        let suffix = self.name.strip_prefix("g_Texture")?;
        if suffix.is_empty()
            || !suffix.chars().all(|character| character.is_ascii_digit())
            || suffix.len() > 1 && suffix.starts_with('0')
        {
            return None;
        }

        suffix
            .parse::<u32>()
            .ok()
            .map(|binding| TextureBindingFact {
                name: self.name,
                descriptor: ProgramDescriptorBinding::set_zero(binding),
            })
    }
}

/// Typed texture binding fact parsed from a source texture name.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TextureBindingFact<'src> {
    /// Source texture name carrying the fact.
    name: &'src str,
    /// Descriptor binding represented by the name.
    descriptor: ProgramDescriptorBinding,
}

impl<'src> TextureBindingFact<'src> {
    /// Reserves this binding for a split texture declaration.
    fn reserve_for(
        self,
        texture: TextureResourceDeclaration<'src>,
        reservations: &mut ProgramBindingReservations<'src>,
    ) -> ShaderResult<()> {
        debug_assert_eq!(self.name, texture.name);
        reservations.reserve_descriptor(self.descriptor, texture.reservation())
    }
}

/// Program-level uniform declaration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct UniformResourceDeclaration<'src> {
    /// Stage containing the source declaration.
    stage: ShaderStageKind,
    /// Preprocessed source containing the declaration.
    module_source: &'src str,
    /// Source type name.
    ty: &'src str,
    /// Source variable name.
    name: &'src str,
    /// Optional array suffix following the declaration name.
    array_suffix: Option<ProgramArraySuffixFact<'src>>,
    /// Explicit layout binding parsed from source, when present.
    explicit_binding: Option<u32>,
}

impl<'src> UniformResourceDeclaration<'src> {
    /// Returns the explicit descriptor binding, when source declared one.
    fn explicit_binding(self) -> Option<u32> {
        self.explicit_binding
    }

    /// Converts this source declaration into a replay-safe program member.
    fn into_supported_member(self) -> ShaderResult<ProgramUniformMember<'src>> {
        let ty = ProgramUniformType::new(self.ty)?.source;
        let array_suffix = self
            .array_suffix
            .map(|suffix| ProgramUniformArraySuffixSource {
                stage: self.stage,
                module_source: self.module_source,
                source: suffix.as_str(),
            })
            .map(TryInto::try_into)
            .transpose()?;
        Ok(ProgramUniformMember {
            ty,
            name: self.name,
            array_suffix: array_suffix.map(|suffix: ProgramUniformArraySuffix<'src>| suffix.source),
            explicit_binding: self.explicit_binding,
        })
    }
}

/// Typed program uniform array suffix parsed by syntax.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramArraySuffixFact<'src> {
    /// Source suffix text, including brackets.
    source: &'src str,
}

impl<'src> ProgramArraySuffixFact<'src> {
    /// Returns the suffix source text, including brackets.
    const fn as_str(self) -> &'src str {
        self.source
    }
}

/// Resolved array suffix for a generated program uniform member.
#[derive(Clone, Debug, Eq, PartialEq)]
struct ProgramUniformArraySuffix<'src> {
    /// Source suffix text, including brackets.
    source: Cow<'src, str>,
}

/// Unresolved source array suffix for a generated program uniform member.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ProgramUniformArraySuffixSource<'src> {
    /// Stage containing the source declaration.
    stage: ShaderStageKind,
    /// Preprocessed source containing the declaration.
    module_source: &'src str,
    /// Source suffix text, including brackets.
    source: &'src str,
}

impl<'src> TryFrom<ProgramUniformArraySuffixSource<'src>> for ProgramUniformArraySuffix<'src> {
    type Error = ShaderError;

    fn try_from(source: ProgramUniformArraySuffixSource<'src>) -> Result<Self, Self::Error> {
        if let Some(count) = source
            .source
            .strip_prefix('[')
            .and_then(|inner| inner.strip_suffix(']'))
            .and_then(|inner| {
                let inner = inner.trim();
                (!inner.is_empty())
                    .then(|| inner.parse::<u32>().ok())
                    .flatten()
            })
        {
            return Ok(Self {
                source: Cow::Owned(format!("[{count}]")),
            });
        }
        let identifier = source
            .source
            .strip_prefix('[')
            .and_then(|inner| inner.strip_suffix(']'))
            .map(str::trim);
        let resolved = identifier.and_then(|identifier| {
            let mut chars = identifier.chars();
            let first = chars.next()?;
            if !(first.is_ascii_alphabetic() || first == '_')
                || !chars.all(|character| character.is_ascii_alphanumeric() || character == '_')
            {
                return None;
            }
            let value = LeadingObjectMacroDefinitions {
                source: source.module_source,
            }
            .value(identifier)?;
            value.parse::<u32>().ok().map(|count| format!("[{count}]"))
        });
        if let Some(resolved) = resolved {
            return Ok(Self {
                source: Cow::Owned(resolved),
            });
        }
        Err(ShaderError::invalid_request(format!(
            "unresolved GlobalUniforms member array suffix `{}` in {:?} stage",
            source.source, source.stage
        )))
    }
}

/// Contiguous object-like `#define`s at the beginning of a preprocessed stage.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LeadingObjectMacroDefinitions<'src> {
    /// Preprocessed stage source.
    source: &'src str,
}

impl<'src> LeadingObjectMacroDefinitions<'src> {
    /// Returns the value for a simple leading object macro.
    fn value(self, name: &str) -> Option<&'src str> {
        for line in self.source.lines() {
            let trimmed = line.trim_start();
            let Some(rest) = trimmed.strip_prefix("#define") else {
                break;
            };
            let rest = rest.trim_start();
            let name_len = rest
                .char_indices()
                .take_while(|(index, character)| {
                    if *index == 0 {
                        character.is_ascii_alphabetic() || *character == '_'
                    } else {
                        character.is_ascii_alphanumeric() || *character == '_'
                    }
                })
                .map(|(index, character)| index + character.len_utf8())
                .last()
                .unwrap_or_default();
            if rest.get(..name_len)? != name {
                continue;
            }
            let value = rest[name_len..].trim_start();
            if !value.is_empty() {
                return Some(value);
            }
        }
        None
    }
}

/// Typed layout binding fact parsed from syntax layout text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LayoutBindingFact {
    /// Descriptor set index.
    set: Option<u32>,
    /// Descriptor binding index.
    binding: u32,
}

impl LayoutBindingFact {
    /// Parses the first explicit layout binding fact from a source
    /// declaration's token range.
    fn from_declaration<'src>(
        module: &ShaderModule<'src>,
        declaration: &crate::syntax::ShaderDeclaration<'src>,
    ) -> Option<Self> {
        let tokens = module.tokens();
        let span = declaration.span();
        let start = tokens
            .iter()
            .position(|token| token.span.start() >= span.start())?;
        let end = tokens
            .iter()
            .position(|token| token.span.end() > span.end())
            .unwrap_or(tokens.len());
        let search = TokenSearch::new(tokens);
        let mut index = start;
        while index < end {
            if !matches!(tokens[index].kind, TokenKind::Identifier("layout")) {
                index += 1;
                continue;
            }
            let open = search.next_non_comment(index + 1)?;
            if open >= end || !matches!(tokens[open].kind, TokenKind::LeftParen) {
                index += 1;
                continue;
            }
            let mut depth = 0usize;
            let mut close = None;
            for (candidate, token) in tokens.iter().enumerate().take(end).skip(open) {
                match token.kind {
                    TokenKind::LeftParen => depth += 1,
                    TokenKind::RightParen => {
                        depth = depth.checked_sub(1)?;
                        if depth == 0 {
                            close = Some(candidate);
                            break;
                        }
                    }
                    _ => {}
                }
            }
            let close = close?;
            let qualifier = LayoutQualifierTokens {
                tokens,
                start: open + 1,
                end: close,
            };
            if let Some(binding) = qualifier.value_for("binding") {
                return Some(LayoutBindingFact {
                    set: qualifier.value_for("set"),
                    binding,
                });
            }
            index = close + 1;
        }
        None
    }

    /// Returns the descriptor set/binding pair for this layout fact.
    const fn descriptor(self) -> ProgramDescriptorBinding {
        ProgramDescriptorBinding {
            set: match self.set {
                Some(set) => set,
                None => 0,
            },
            binding: self.binding,
        }
    }

    /// Reserves this binding for a kept source resource.
    fn reserve_for<'src>(
        self,
        resource: KeptResourceDeclaration<'src>,
        reservations: &mut ProgramBindingReservations<'src>,
    ) -> ShaderResult<()> {
        reservations.reserve_descriptor(self.descriptor(), resource.reservation())
    }
}

/// Token range inside one layout qualifier.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LayoutQualifierTokens<'tokens, 'src> {
    /// Module tokens.
    tokens: &'tokens [Token<'src>],
    /// First token inside the layout parentheses.
    start: usize,
    /// Closing parenthesis token index.
    end: usize,
}

impl LayoutQualifierTokens<'_, '_> {
    /// Parses an integer-valued layout field inside this layout qualifier.
    fn value_for(self, name: &str) -> Option<u32> {
        let search = TokenSearch::new(self.tokens);
        for index in self.start..self.end {
            if !matches!(self.tokens[index].kind, TokenKind::Identifier(identifier) if identifier == name)
            {
                continue;
            }
            let equals = search.next_non_comment(index + 1)?;
            if equals >= self.end
                || !matches!(self.tokens[equals].kind, TokenKind::Punctuation('='))
            {
                continue;
            }
            let value = search.next_non_comment(equals + 1)?;
            if value >= self.end {
                continue;
            }
            let TokenKind::Number(text) = self.tokens[value].kind else {
                continue;
            };
            return text.parse::<u32>().ok();
        }
        None
    }
}
